#!/bin/sh -e

[ -f koompilinux.img ] || {
	qemu-img create -f qcow2 koompilinux.img 20G
}

exec qemu-system-x86_64 -enable-kvm \
        -cpu host \
        -drive file=koompilinux.img,if=virtio \
        -netdev user,id=vmnic,hostname=KOOMPI \
        -device virtio-net,netdev=vmnic \
        -device virtio-rng-pci \
        -m 2G \
        -smp 2 \
        -monitor stdio \
        -name "KOOMPILinux VM" \
        -boot d -cdrom koompilinux-20210209.iso
