#!/bin/bash

KFSMOUNT=$1

if [ ! "$KFSMOUNT" ]; then
	cat << EOF
Usage:
  $(basename $0) <path to install>
  
Example:
  $(basename $0) /mnt/kfs
  
Note:
  You should first configure partition then mount it somewhere
  
EOF
	exit 1
fi

if ! mountpoint -q $KFSMOUNT; then
	echo "'$KFSMOUNT' is not a mountpoint!"
	exit 1
fi

if [ -f "/run/initramfs/ram/root.sfs" ]; then
	ROOTSFS="/run/initramfs/ram/root.sfs"
elif [ -f "/run/initramfs/medium/kfs/root.sfs" ]; then
	ROOTSFS="/run/initramfs/medium/kfs/root.sfs"
else
	echo "squashed image not found!"
	exit 1
fi

unsquashfs -f -i -d $KFSMOUNT $ROOTSFS

if [ "$?" = "0" ]; then
	echo
	echo "Successfully installed to '$KFSMOUNT'"
	echo
	echo "Run 'kfs-chroot $KFSMOUNT' to chroot into $KFSMOUNT."
	echo "Then start configure your new installation."
else
	echo "failed to install kfs system"
	exit 1
fi

exit 0
