#!/bin/bash
# Author < HangsiaHONG hangsia@koompi.org >

CWD=$PWD
source $CWD/config

cd /sources
tar -xf psmisc-23.3.tar.xz
cd psmisc-23.3

./configure --prefix=/usr

make -j1

make install

mv -v /usr/bin/fuser   /bin
mv -v /usr/bin/killall /bin


cd /sources
rm -rf psmisc-23.3