#!/bin/bash
# Author < HangsiaHONG hangsia@koompi.org >

CWD=$PWD
source $CWD/config

cd /sources
tar -xf gettext-0.21.tar.xz
cd gettext-0.21


./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/gettext-0.21


make -j1
#make check
make install
chmod -v 0755 /usr/lib/preloadable_libintl.so

cd /sources
rm -rf gettext-0.21