#!/bin/bash
# Author < HangsiaHONG hangsia@koompi.org >

CWD=$PWD
source $CWD/config

cd /sources
tar -xf gdbm-1.18.1.tar.gz
cd gdbm-1.18.1

sed -r -i '/^char.*parseopt_program_(doc|args)/d' src/parseopt.c

./configure --prefix=/usr \
    --disable-static \
    --enable-libgdbm-compat

make
#make check

make install

cd /sources
rm -rf gdbm-1.18.1
