#!/bin/bash
# Author < HangsiaHONG hangsia@koompi.org >

CWD=$PWD
source $CWD/config

cd /sources
tar -xf XML-Parser-2.46.tar.gz
cd XML-Parser-2.46

perl Makefile.PL
make

#make test
make install

cd /sources
rm -rf XML-Parser-2.46
