#!/bin/bash
# Author < HangsiaHONG hangsia@koompi.org >

CWD=$PWD
source $CWD/config

cd /sources
tar -xf autoconf-2.69.tar.xz
cd autoconf-2.69

sed -i '361 s/{/\\{/' bin/autoscan.in

./configure --prefix=/usr

make
# make check
make install


cd /sources
rm -rf autoconf-2.69