#!/bin/bash
# Author < HangsiaHONG hangsia@koompi.org >

CWD=$PWD
source $CWD/config

cd /sources
tar -xf diffutils-3.7.tar.xz
cd diffutils-3.7

./configure --prefix=/usr

make
#make check
make install


cd /sources
rm -rf diffutils-3.7