#!/bin/bash
# Author < HangsiaHONG hangsia@koompi.org >

CWD=$PWD
source $CWD/config

cd /sources
tar -xf groff-1.22.4.tar.gz
cd groff-1.22.4

PAGE= --prefix=/usr <paper_size >./configure

make

make install

cd /sources
rm -rf groff-1.22.4
