#!/bin/bash
# Author < HangsiaHONG hangsia@koompi.org >

CWD=$PWD
source $CWD/config

cd /sources
tar -xf gzip-1.10.tar.xz
cd gzip-1.10

./configure --prefix=/usr

make
#make check
make install

mv -v /usr/bin/gzip /bin


cd /sources
rm -rf gzip-1.10