#!/bin/bash
# Author < HangsiaHONG hangsia@koompi.org >

CWD=$PWD
source $CWD/config

cd /sources
tar -xf iana-etc-20200821.tar.gz
cd iana-etc-20200821

cp services protocols /etc

cd /sources
rm -rf iana-etc-20200821
