#!/bin/bash
# Author < HangsiaHONG hangsia@koompi.org >

CWD=$PWD
source $CWD/config

cd /sources
tar -xf make-4.3.tar.gz
cd make-4.3

./configure --prefix=/usr

make -j1
#make check
make install


cd /sources
rm -rf make-4.3