#!/bin/bash
# Author < HangsiaHONG hangsia@koompi.org >

CWD=$PWD
source $CWD/config

cd /sources
tar -xf sysvinit-2.97.tar.xz
cd sysvinit-2.97

patch -Np1 -i ../sysvinit-2.97-consolidated-1.patch


make -j1

make install

cd /sources
rm -rf sysvinit-2.97