#!/bin/bash
# Author < HangsiaHONG hangsia@koompi.org >

CWD=$PWD
source $CWD/config

cd /sources
tar -xf lfs-bootscripts-20200818.tar.xz
cd lfs-bootscripts-20200818

make install
cd /sources
rm -rf lfs-bootscripts-20200818
