#!/bin/bash
# Author < HangsiaHONG hangsia@koompi.org >

CWD=$PWD
source $CWD/config

cd /sources
tar -xf libisoburn-1.5.2.tar.gz
cd libisoburn-1.5.2

./configure --prefix=/usr              \
            --disable-static           \
            --enable-pkg-check-modules &&
make

make install