#!/bin/bash
# Author < HangsiaHONG hangsia@koompi.org >

CWD=$PWD
source $CWD/config


cd /sources
tar -xf gettext-0.21.tar.xz
cd gettext-0.21

./configure --disable-shared
make
cp -v gettext-tools/src/{msgfmt,msgmerge,xgettext} /usr/bin


cd /sources
rm -rf gettext-0.21
