#!/bin/bash
# Author < HangsiaHONG hangsia@koompi.org >

CWD=$PWD
source $CWD/config

cd /sources
tar -xf texinfo-6.7.tar.xz
cd texinfo-6.7


./configure --prefix=/usr

make
make install

cd /sources
rm -rf texinfo-6.7
