#!/bin/bash
# Author < HangsiaHONG hangsia@koompi.org >



cd $KFS/sources
tar -xf glibc-2.32.tar.xz 
cd glibc-2.32

case $(uname -m) in
    i?86)   ln -sfv ld-linux.so.2 $KFS/lib/ld-lsb.so.3
    ;;
    x86_64) ln -sfv ../lib/ld-linux-x86-64.so.2 $KFS/lib64
            ln -sfv ../lib/ld-linux-x86-64.so.2 $KFS/lib64/ld-lsb-x86-64.so.3
    ;;
esac

patch -Np1 -i ../glibc-2.32-fhs-1.patch

mkdir -v build
cd       build

../configure                             \
      --prefix=/usr                      \
      --host=$KFS_TGT                    \
      --build=$(../scripts/config.guess) \
      --enable-kernel=3.2                \
      --with-headers=$KFS/usr/include    \
      libc_cv_slibdir=/lib

make
make install

cd $KFS/sources
rm -rf glibc-2.32
