#!/bin/bash
# Author < HangsiaHONG hangsia@koompi.org >

cd $KFS/sources
tar -xf diffutils-3.7.tar.xz
cd diffutils-3.7

./configure --prefix=/usr --host=$KFS_TGT
make
make install 

cd $KFS/sources
rm -rf diffutils-3.7