#!/bin/bash
# Author < HangsiaHONG hangsia@koompi.org >

CWD=$PWD
source $CWD/config
TCDIR=$CWD/toolchain

cd $KFS/sources
tar -xf gawk-5.1.0.tar.xz 
cd gawk-5.1.0

sed -i 's/extras//' Makefile.in

./configure --prefix=/usr   \
            --host=$KFS_TGT \
            --build=$(./config.guess)

make
make install

cd $KFS/sources
rm -rf gawk-5.1.0