#!/bin/bash
# Author < HangsiaHONG hangsia@koompi.org >

CWD=$PWD
source $CWD/config
TCDIR=$CWD/toolchain

cd $KFS/sources
tar -xf grep-3.4.tar.xz
cd grep-3.4

./configure --prefix=/usr   \
            --host=$KFS_TGT \
            --bindir=/bin

make
make install

cd $KFS/sources
rm -rf grep-3.4