#!/bin/bash
# Author < HangsiaHONG hangsia@koompi.org >

CWD=$PWD
source $CWD/config
TCDIR=$CWD/toolchain

cd $KFS/sources
tar -xf gzip-1.10.tar.xz
cd gzip-1.10

./configure --prefix=/usr --host=$KFS_TGT
make
make install
mv -v $KFS/usr/bin/gzip $KFS/bin

cd $KFS/sources
rm -rf gzip-1.10